export const welcomeList = [
  {
    text: '欢迎来到Taurion！',
    source: "T-brain",
    autoNext: true,
    id: 1,
  },
  {
    text: '我是T-brain,你的AI金融助理.',
    source: "T-brain",
    autoNext: true,
    id: 2,
  },
  {
    text: "我有强大的大脑,可以帮你汇总海量信息和解答你任何金融疑惑.",
    source: "T-brain",
    autoNext: true,
    id: 3,
  },
  {
    text: "我很荣幸可以成为你的“金融副驾驶.",
    source: "T-brain",
    autoNext: true,
    id: 4,
  },
  {
    text: '你可以问我任何关于金融的问题,我会尽力帮你解答.',
    source: "T-brain",
    autoNext: true,
    id: 5,
  },
  {
    taskText: '接下来,让我们先完成第一项任务',
    autoNext: false,
    type: "taskStart",
    startBtnShow: true,
    source: "T-brain",
    id: 6,
  },
  {
    source: "T-brain",
    type: "task",
    taskName: '任务一',
    autoNext: true,
    title: '添加自选加密货币',
    canSkip: false,
    searchType: 'coin',
    finish: false,
    desc: '添加自选后，Taurion会为你的自选每日生成市场焦点，协助你减少市场噪音',
    id: 7,
  },
  {
    text: '你可以通过向我提问或自行搜索来快速增加自选加密货币',
    autoNext: false,
    source: "T-brain",
    needPushHotCoin: true,
    id: 8,
  },
  // 此处需要插入 自选加密货币推荐数据
  {
    text: "🎉 很好我们完成了第一项任务",
    autoNext: true,
    source: "T-brain",
    id: 9,
  },
  {
    taskText: '接下来,让我们完成第二项任务',
    type: "taskStart",
    autoNext: false,
    startBtnShow: true,
    source: "T-brain",
    id: 10,
  },
  {
    source: "T-brain",
    type: "task",
    taskName: '任务二',
    autoNext: true,
    title: '添加监控',
    searchType: 'monitor',
    canSkip: true,
    finish: false,
    desc: 'Taurion会作为你的AI分身，对于你的监控内容总结关键要点，并帮助你进一步理解关键信息。',
    id: 11,
  },
  {
    text: '你可以通过向我提问或自行搜索来快速增加监控',
    source: "T-brain",
    autoNext: false,
    needPushHotMonitor: true,
    id: 12,
  },
  // 此处插入监控推荐数据
  {
    text: "🎉 赞，我相信你会对我监控的效果感到满意的",
    source: "T-brain",
    autoNext: true,
    id: 13,
  },
  {
    text: '🎁 至此我们已经完成了所有任务',
    source: "T-brain",
    autoNext: true,
    id: 14,
  },
  {
    taskText: '让我们启动Taurion吧？',
    type: "taskFinish",
    startBtnShow: true,
    source: "T-brain",
    autoNext: false,
    id: 15,
  },
]
